version: '3.7'

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    hostname: adminer
    ports:
      - "5433:8080"
    environment:
      ADMINER_TITLE: Adminer
      ADMINER_USER: adminer
      ADMINER_PASSWORD: adminer
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/adminer.php"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
